### ISSUE TITLE
提下我的疑惑

### ISSUE THREAD

**Issue by oubowu** [alibaba/JAndFix#1]
这个东西怎么以补丁的形式下发，我看demo是直接在代码替换方法，但是对线上版本修复了某个方法，怎么去做热更新？然后你在对比方案那里易用性标的是好，但是你们这里也用了大量反射方法

**Comment by QinJingchao** [comment]
hi 你好！
“这个东西怎么以补丁的形式下发”，我这个是热修复的工具，并不是工程，工具只提供热修复。补丁的下发还是要基于网络和打dex的插件，这些知识我个人认为是工具的扩展功能，不应该工具本身去提供这些功能，比如dex生成，下发，加载。如有需要可以借鉴AndFix，它有完整的工程，你可以用AndFixdex生成，下发逻辑，然后调用我的修复功能。
“然后你在对比方案那里易用性标的是好”，并不是反射就不易用了，这里的易用性，只的是你写patch的代码时候方便，要知道dexposed、robust写patch的时候都需要通过反射去调用原来的对象，而我的这个方案你可以按正常逻辑直接写你的patch，不需要发射！
感谢提问！

**Comment by oubowu** [comment]
感谢回复
